env_key:
  - braxgeneralized-halfcheetah
  - braxpositional-halfcheetah
  - braxspring-halfcheetah
  - braxmjx-halfcheetah

device: cuda
num_env: 1000
max_episode_length: 1000
action_repeat: 1  # todo
framestack: 1 # todo
