env_key:
  - mujoco-ant
  #- braxgeneralized-ant
  #- braxpositional-ant
  #- braxspring-ant
  #- braxmjx-ant

device: cuda
num_env: 200
max_episode_length: 1000
action_repeat: 1  # todo
framestack: 1 # todo
