env_key:
  - mujoco-ant
  - braxgeneralized-ant
  - braxpositional-ant
  - braxspring-ant
  - braxmjx-ant

device: cuda
num_env: 100
max_episode_length: 1000
last_action: True
action_repeat: None  # todo
framestack: 10 #8 # todo
mat_framestack_instead: False

use_randomization: true
min_mass: 4
max_mass: 6
