alg: "sac"

total_timesteps: 75_000_000
buffer_size: 1e6
gamma: 0.99
tau: 0.005
batch_size: 128 #128 #4096
learning_starts: 5e3
policy_lr: 3e-4
q_lr: 1e-3
policy_frequency: 2
target_network_frequency: 2   # or 1
alpha: 0.2
autotune: True"