env_key:
  - mujoco-inverted_pendulum
  - braxgeneralized-inverted_pendulum
  - braxpositional-inverted_pendulum
  - braxspring-inverted_pendulum
  - braxmjx-inverted_pendulum

device: cuda
num_env: 100
max_episode_length: 1000
last_action: True
action_repeat: None  # todo

#framestack: 0 #10 #10 #8 # todo
#mat_framestack_instead: False

dr_percent_below: 1.0
dr_percent_above: 1.0
dr_do_on_reset: False
dr_do_on_N_step: 0
dr_do_at_creation: False
