defaults:
  #- env: ant-no-dr
  - wandb: wandb
  - rl: ppo
  - env_method: vanilla_ppo
  - multienv: brax2brax
  - env@train_env: go1-with-dr
  - env@eval_env: go1-with-dr
  - rl@ppo: ppo
  - rl@sac: sac
  - rl@rma: rma

#hydra:
#  sweeper:
#    params:
#      multienv.env@train: ant-no-dr,ant-with-dr