defaults:
  - env@train:
      - ant-gen
  - env@eval:
    - ant-mujoco_mjx

device: cuda # falls back to cpu if needed no matter what

do_powerset: False # if true, eval will be disabled and taken as the left-outs for every set in the powerset of the train envs
num_env: None
max_episode_length: None
action_repeat: None
framestack: None

eval_freq: 10000000
num_eval_steps: 500
video_freq: None
num_video_steps: 100