#defaults:
#  - env@train:
#    - ant-with-dr
#  - env@eval:
#    - ant-with-dr

device: cuda # falls back to cpu if needed no matter what

do_powerset: False # False #True # if true, eval will be disabled and taken as the left-outs for every set in the powerset of the train envs
min_powerset_len: None
max_powerset_len: None
do_powerset_id: None  # if non-None, will ONLY run this particular ID

num_env: None
max_episode_length: None
action_repeat: None
framestack: None
mat_framestack_instead: None

eval_freq: 10000000
num_eval_steps: 100
do_eval_video: True